#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist >/dev/null 2>&1 &
sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=space_changed action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=window_created action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=window_focused action="sketchybar -m --trigger yabai_window &> /dev/null"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=system_woke action="brew services restart sketchybar"

# global settings
yabai -m config external_bar all:0:50
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse on
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_zoom_persist off
yabai -m config window_topmost off
yabai -m config window_shadow float
yabai -m config auto_balance off
yabai -m config split_ratio 0.50

# mouse settings
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move   # left click + drag
yabai -m config mouse_action2 resize # right click + drag
yabai -m config mouse_drop_action swap

# binary space partitioning, stack or float
yabai -m config layout bsp

# padding
yabai -m config top_padding 15
yabai -m config bottom_padding 5
yabai -m config left_padding 15
yabai -m config right_padding 15
yabai -m config window_gap 10

# window border
yabai -m config window_border on
yabai -m config window_border_hidpi on
yabai -m config window_border_blur off
yabai -m config window_border_width 3
yabai -m config window_border_radius 5
yabai -m config active_window_border_color 0xffb4befe
yabai -m config normal_window_border_color 0xff1a1a29
yabai -m config insert_feedback_color 0xffb4befe

# opacity
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.15
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Alfred-Preferences$" manage=off
yabai -m rule --add app="^Amphetamine$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^The Unarchiver$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^DaisyDisk$" manage=off
yabai -m rule --add app="^Hazel$" manage=off
yabai -m rule --add app="^IINA$" manage=off
yabai -m rule --add app="^Google Drive$" manage=off
yabai -m rule --add app="^WD Drive Utilities$" manage=off
yabai -m rule --add app="^SpaceLauncher$" manage=off
yabai -m rule --add app="^Fantastical$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Loom$" manage=off
yabai -m rule --add app="^Loom$" title="^Loom | Loom Recorder Settings$" manage=off sticky=on
yabai -m rule --add app="^Loom$" title="^Loom | Loom Camera$" manage=off sticky=on
